Implemented and deployed validate_type_for_device<T>(q)
This check would produce more succint error message:

```
In [1]: import dpctl.tensor as dpt

In [2]: dpt.arange(0, 10, dtype='f8')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 dpt.arange(0, 10, dtype='f8')

File ~/repos/dpctl/dpctl/tensor/_ctors.py:603, in arange(start, stop, step, dtype, device, usm_type, sycl_queue)
    601     _step = sc_ty(1)
    602 _start = _first
--> 603 hev, _ = ti._linspace_step(_start, _step, res, sycl_queue)
    604 hev.wait()
    605 if is_bool:

RuntimeError: Device Intel(R) Graphics [0x9a49] does not support type 'double'
```