Pin conda-build to most recent working version
Works around issues with lief that cause failures after build completes with the message
```
AttributeError: module 'lief._lief.ELF' has no attribute 'ELF_CLASS'
```