Improved error handling for usm_ndarray.__setitem__
```python
import dpctl.tensor as dpt, numpy as np

u, n = dpt.empty(5), np.ones(5, dtype="O")
u[...] = n
```

This example used to raise a cascade of exceptions starting
with cryptic  "RuntimeError: Unrecogized typenum 17 encountered.",
where typenum 17 corresponds to type object.

After this change, the error message is crisper:

```
ValueError: Input of type <class 'numpy.ndarray'> can not be \
    assigned to usm_ndarray because of unsupported data \
    type 'object'
```